import { GeometryInput, MaterialInput, ConditionInput, CalculationResult } from '../types';

export const downloadJSON = (
  geo: GeometryInput,
  mat: MaterialInput,
  cond: ConditionInput,
  res: CalculationResult
) => {
  const data = {
    geometry: geo,
    materials: mat,
    conditions: cond,
    results: res,
    meta: {
      app: "CryoBolt Calc",
      version: "1.1.0",
      date: new Date().toISOString()
    }
  };
  
  const filename = `CryoBolt_Data_${new Date().toISOString().split('T')[0]}.json`;
  const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
};

export const downloadTextReport = (
  geo: GeometryInput,
  mat: MaterialInput,
  cond: ConditionInput,
  res: CalculationResult
) => {
  const pad = (label: string, val: any, unit: string = "") => {
    return `${label.padEnd(40)}: ${String(val).padEnd(12)} ${unit}`;
  };

  const lines = [
    "================================================================",
    "       LOW TEMPERATURE BOLT PRELOAD CALCULATION DRAFT",
    "                 低温螺栓预紧力计算书",
    "================================================================",
    `REF: CN 105574341 B`,
    `Date: ${new Date().toLocaleString()}`,
    "",
    "1. Design Parameters (设计参数)",
    "----------------------------------------------------------------",
    pad("Bolt Diameter (d)", geo.d, "mm"),
    pad("Bolt Length (Lb)", geo.Lb, "mm"),
    pad("Bolt Area (Ab)", geo.Ab.toFixed(2), "mm²"),
    pad("Clamp Outer Dia (da)", geo.da, "mm"),
    pad("Clamp Length (L)", geo.L, "mm"),
    pad("Beta Factor (β)", geo.beta, ""),
    pad("Alpha Factor (α)", geo.alpha, ""),
    "",
    "2. Material Properties (材料属性)",
    "----------------------------------------------------------------",
    pad("Bolt Modulus (Eb)", mat.Eb.toExponential(2), "MPa"),
    pad("Flange Modulus (Ec)", mat.Ec.toExponential(2), "MPa"),
    pad("Bolt CTE (αb)", mat.alpha_b.toExponential(2), "1/°C"),
    pad("Flange CTE (αc)", mat.alpha_c.toExponential(2), "1/°C"),
    pad("Yield Strength (σs)", mat.sigma_s, "MPa"),
    "",
    "3. Stiffness Calculation (刚度计算)",
    "----------------------------------------------------------------",
    pad("Bolt Stiffness (kb)", res.kb.toExponential(3), "N/mm"),
    pad("Nut Stiffness (kn)", res.kn.toExponential(3), "N/mm"),
    pad("Head Stiffness (kh)", res.kh.toExponential(3), "N/mm"),
    pad("Washer Stiffness (kw)", res.kw.toExponential(3), "N/mm"),
    pad("Clamp Stiffness (kc)", res.kc.toExponential(3), "N/mm"),
    pad("Joint Stiffness (kc')", res.kc_prime.toExponential(3), "N/mm"),
    `Method: ${res.kc_formula_used}`,
    "",
    "4. Coefficients (系数)",
    "----------------------------------------------------------------",
    pad("Deformation Coeff (m)", res.m.toFixed(4), ""),
    "",
    "5. Operating Conditions (工况条件)",
    "----------------------------------------------------------------",
    pad("Install Temp (T0)", cond.T_room, "°C"),
    pad("Working Temp (T)", cond.T_work, "°C"),
    pad("Delta T", res.deltaT, "°C"),
    pad("Ext. Load (P)", cond.P, "kN"),
    pad("Stress Conc. Factor (a)", cond.a, ""),
    pad("Min Preload Coeff (b)", cond.b, ""),
    "",
    "6. Results (计算结果)",
    "----------------------------------------------------------------",
    pad("Thermal Force Term", (res.thermalForceChange/1000).toFixed(3), "kN"),
    "",
    "Rec. Preload (Room Temp) / 常温推荐预紧力:",
    pad("Standard (Eq 10)", (res.Fn_simple / 1000).toFixed(2), "kN"),
    pad("Min Limit (Eq 13)", (res.Fn_min / 1000).toFixed(2), "kN"),
    pad("Max Limit (Eq 13)", (res.Fn_max / 1000).toFixed(2), "kN"),
    "",
    "================================================================",
    "Generated by CryoBolt Calc",
    "================================================================"
  ];

  const content = lines.join('\n');
  const filename = `CryoBolt_Report_${new Date().toISOString().split('T')[0]}.txt`;
  const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
};